### ISSUE TITLE
Build errors, if no target field is present

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#102]
**Describe the bug**
When running `clio build` without a `[target.<target>]` section in toml, the build fails

**To Reproduce**
1. Generate a project with `clio new foo`
2. Change into the directory
3. Open up the toml manifest and remove the `[target.node]` section:
4. Run build
5. Admire error

```
Error: Cannot use 'in' operator to search for 'node' in undefined
```

**Expected behavior**
In case no target is specified, the default `target` field from the `build` section should be used as a target directory. The following should therefore be a valid toml config. Notice the missing `[target.node]` section.

```toml
title = "template-node"
description = ""
version = "0.1.0"
license = "MIT"
main = "src/main.clio"
authors = [ "Your Name <you@example.com>" ]
keywords = ""

[build]
directory = "build"
target = "node"

[scripts]
test = "No tests specified"

[dependencies]
stdlib = "latest"
```

**Versions (please complete the following information):**
 - OS: macOS Catalina
 - Clio: v0.2.0 dev (da7e238f996b9ea1b84643ccc0b0aa24b877b962)
 - Node: v12.13.1
 - NPM: 6.13.4
 
**Possible solutions**
 - No default value in package config

**Additional Notes**
Might be fixed with #98, wait for it to merge
