### ISSUE TITLE
Specify Target Platform in toml

### ISSUE THREAD

**Issue by garritfra** [clio-lang/clio#117]
The current implementation does not distinguish between platforms and targets. This issue aims to seperate the two clearly. 

Currently, this is a valid target in toml: 

```toml
[target.node]
directory = "src"
target = "node"
```

Where `node` is a custom target name that is checked against a set of available targets (currently `node` and `web`). Initially, this field was intended to be used as a build variant (E.g. if the user wants to have a free and a paid variant of the application, he would create a `free` and a `paid` target). To resolve this and have the best from both worlds, we have discussed the following solution.

The following example shows possible target definitions:
```toml

# source directory is "src"
# builds to directory ps4/
# Uses the "web" target module
[target.ps4]
directory = "src"
target = "ps4"
platform = "web"

# Source directory is "serverSrc/"
# Builds to directory "server/"
# Platform defaults to "node"
[target.server]
directory = "serverSrc"
```

A **target** means a variant of the build. It can be whatever the user wants.

A **platform** tells the compiler how the application should be built. Essentially, a platform is an interface with a `build` and a `run` method that the compiler hooks into.

### Room for discussion

We had the idea to make the platform be importable from an external source. Either using it like this: 
```toml
[target.ps4]
directory = "src"
target = "ps4"
platform = "github:foouser/clio-ps4-platform"
```

or by adding it as a dependency:

```toml
[target.ps4]
directory = "src"
target = "ps4"
platform = "clio-ps4-platform"

[dependencies]
"npm:clio-ps4-platform" = "latest"
```

However, we should discuss if this should be part of this issue, or another one.

### Additional context
For this issue to be worked on, #98 needs to be merged.
